---
Name: focuspoint
After: 'framework/*','cms/*'
---
Image:
  extensions:
    - FocusPointImage

#FocusPointField:
#  debug: true
#Injector:
#  ImagickBackend:
#    class: "FPImagickBackend"
#  Image:
#    class: FPImage
